project:
  folder: C:\\auto_projects
  workspace: C:\\auto_workspace

spring:
  application:
    name: HikariCP测试
  # 数据源的配置
  datasource:
    # 连接池的配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
